spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: root
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  servlet:
    context-path: /internal
  port: 8285
